// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApoRnKiuyQUdsr-FVXv7OCQwxPLbog5Jo',
    appId: '1:545946988083:android:d654ff9a5435007c36bd46',
    messagingSenderId: '545946988083',
    projectId: 'reddit-app-5aa05',
    storageBucket: 'reddit-app-5aa05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgvAz_Bz5ZKx199QseH-EqXQ4BVNMmb-I',
    appId: '1:545946988083:ios:d2c6a53a89752fa636bd46',
    messagingSenderId: '545946988083',
    projectId: 'reddit-app-5aa05',
    storageBucket: 'reddit-app-5aa05.appspot.com',
    androidClientId:
        '545946988083-srq095009p4q4vv09m39ovd5i0fjnf4g.apps.googleusercontent.com',
    iosClientId:
        '545946988083-m14qphr3aq3l7bak0jprb22oarns5jk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );
}
